#!/usr/bin/env bash

set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

git_rev_docker_args_deploy() {
  local APP="$1"
  local IMAGE_TAG="$2"
  local STDIN=$(cat)
  local output=""

  # Ensure the .dokku-git-rev file actually exists
  if test -f "$DOKKU_ROOT/$APP/.dokku-git-rev"; then
    # Grab the REV
    local GIT_REV=$(tail -1 "$DOKKU_ROOT/$APP/.dokku-git-rev")
    local GIT_BRANCH=$(tail -1 "$DOKKU_ROOT/$APP/.dokku-git-branch")
    local output="$output -e GIT_REV=$GIT_REV -e GIT_BRANCH=$GIT_BRANCH"
    dokku_log_info1 "Adding GIT_REV ($GIT_REV), GIT_BRANCH ($GIT_BRANCH) to environment..."
  fi

  echo -n "$STDIN$output"
}

git_rev_docker_args_deploy "$@"
